name: Process Mitre Data

on:
  pull_request:
    paths:
      - 'mitre_input/**'
    branches: 
      - main

permissions:
  contents: write

jobs:
  process_mitre_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.2.2

    - name: Get python to run script
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run python script
      run: |
        python main.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: 'Added Converted MITRE Navigator JSON file to output'
        file_pattern: 'mitre_output/*'
